theme = "vscode"

[editor]
mouse = false
rulers = [80]
bufferline = "multiple"
color-modes = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.whitespace.render]
tab = "all"

[editor.indent-guides]
render = true
character = "⸽"

[editor.statusline]
right = ["version-control", "diagnostics", "selections", "register", "position", "file-encoding"]

[editor.smart-tab]
enable = false

[keys.normal]

# HJKL -> ,AEI
"," = "move_char_left"
a = "move_visual_line_down"
e = "move_visual_line_up"
i = "move_char_right"

# A-,i buffer navigation
"A-," = "jump_view_left"
"A-a" = "jump_view_down"
"A-e" = "jump_view_up"
"A-i" = "jump_view_right"

# Tab buffer navigation
"S-tab" = "goto_previous_buffer"
"tab" = "goto_next_buffer"

# X -> L
l = "extend_to_line_bounds"
L = "extend_line_below"

# A -> H
h = "append_mode"
H = "insert_at_line_end"

# , -> J
j = "keep_primary_selection"
J = "remove_primary_selection"

# J -> C
C = "join_selections_space"

# I -> S
s = "insert_mode"
S = "insert_at_line_start"

# E -> T
t = "move_next_word_end"
T = "move_next_long_word_end"

# ;: -> K;
";" = "command_mode"
k = "collapse_selection"
K = "flip_selections"

# C -> X
x = "copy_selection_on_next_line"
X = "copy_selection_on_prev_line"

# S -> #
"#" = "select_regex"
"@" = "split_selection_on_newline"

# Case switching
"`" = "switch_to_lowercase"
"~" = "switch_to_uppercase"

# Save/Quit shortcuts
C-s = ":wa"
C-q = ":qa"

# Vim compatibility / convenience
G = "goto_last_line"
V = ["select_mode", "extend_to_line_bounds"]
"^" = "goto_line_start"
"$" = "goto_line_end"

# Utility
"*" = ["move_char_right", "move_prev_word_start", "move_next_word_end", "search_selection", "search_next"]

[keys.select]
"," = "extend_char_left"
a = "extend_visual_line_down"
e = "extend_visual_line_up"
i = "extend_char_right"
t = "extend_next_word_end"
T = "extend_next_long_word_end"
tab = "extend_parent_node_end"
S-tab = "extend_parent_node_start"
"^" = "extend_to_line_start"
"$" = "extend_to_line_end"
l = "extend_to_line_bounds"
"*" = ["search_selection", "search_next"]
C = "join_selections_space"
G = "goto_last_line"
v = "expand_selection"
V = "shrink_selection"

[keys.insert]
C-s = ":wa"
