theme = "dark_plus"

[editor]
mouse = false
rulers = [80]
bufferline = "multiple"
color-modes = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.whitespace.render]
tab = "all"

[editor.indent-guides]
render = true

[editor.gutters]
layout = ["diff", "diagnostics", "line-numbers", "spacer"]

[keys.normal]

# HJKL -> ,AEI
"," = "move_char_left"
a = "move_visual_line_down"
e = "move_visual_line_up"
i = "move_char_right"

# A-,i buffer navigation
"A-," = "jump_view_left"
"A-a" = "jump_view_down"
"A-e" = "jump_view_up"
"A-i" = "jump_view_right"

# C-,i buffer navigation
"C-," = "goto_previous_buffer"
"C-i" = "goto_next_buffer"

# X -> L
l = "extend_line_below"
L = "extend_to_line_bounds"
A-l = "shrink_to_line_bounds"

# A -> H
h = "append_mode"
H = "insert_at_line_end"

# , -> J
j = "keep_primary_selection"
J = "remove_primary_selection"

# I -> S
s = "insert_mode"
S = "insert_at_line_start"

# E -> T
t = "move_next_word_end"
T = "move_next_long_word_end"

# ;: -> K;
";" = "command_mode"
k = "collapse_selection"
K = "flip_selections"

# C -> X
x = "copy_selection_on_next_line"
X = "copy_selection_on_prev_line"

# S -> #
"#" = "select_regex"
"@" = "split_selection_on_newline"

# Case switching
"`" = "switch_to_lowercase"
"~" = "switch_to_uppercase"

# Save/Quit shortcuts
C-s = ":wa"
C-q = ":qa"

# Better smart tab
tab = "move_parent_node_end"
S-tab = "move_parent_node_start"

# Misc crap
G = "goto_last_line"

[keys.select]
"," = "extend_char_left"
a = "extend_visual_line_down"
e = "extend_visual_line_up"
i = "extend_char_right"
t = "extend_next_word_end"
T = "extend_next_long_word_end"
tab = "extend_parent_node_end"
S-tab = "extend_parent_node_start"

[keys.insert]
C-s = ":wa"
